# Generated by Django 3.1.7 on 2021-04-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0002_auto_20210417_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendations',
            name='CAPACIDAD',
            field=models.CharField(default='500gb', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recomendations',
            name='CPU',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='recomendations',
            name='GPU',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='recomendations',
            name='HDD',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='recomendations',
            name='RAM',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recomendations',
            name='SSD',
            field=models.BooleanField(),
        ),
    ]
